[tool.poetry]
name = "dbt-jornada"
version = "0.1.0"
description = ""
authors = ["Caique Godoy <caiquecgodoy@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
